name: debug

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Show IP info
        run: |
          curl ifconfig.io
          echo "runner:runner" | sudo chpasswd
          sudo systemctl start ssh

      - name: Download and setup Xray
        run: |
          # 下载 Xray 二进制
          sudo mkdir -p /var/log/v2ray
          sudo chmod 755 /var/log/v2ray
          curl -L https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o /tmp/Xray.zip
          unzip /tmp/Xray.zip -d /tmp/xray-tmp
          sudo cp /tmp/xray-tmp/xray /usr/local/bin/xray
          sudo chmod +x /usr/local/bin/xray

          # 下载 Xray 配置文件
          sudo mkdir -p /etc/xray
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/V2Ray/config.json -o config.json
          sudo mv config.json /etc/xray/

          # 下载并安装 systemd 服务文件
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/V2Ray/xray.service -o xray.service
          sudo mv xray.service /etc/systemd/system/
          sudo /usr/local/bin/xray -test -c /etc/xray/config.json

      - name: Start Xray service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable xray
          sudo systemctl start xray
          sudo systemctl status xray --no-pager

      - name: Install latest cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/
          cloudflared --version
          sudo cloudflared service install eyJhIjoiOGQyMDg4NjE0Nzg1N2EwY2RjYzhkYjc3OGU4YjZlZjciLCJ0IjoiOWJhOTY3OTEtOTc5MC00ZGM3LWFmZTYtM2I5NjZlNDVjZWJiIiwicyI6IlpUSTBPREExWkRVdE1HTXhZUzAwTVRkbExXRTFabVl0Tnpkak9UQmlPR1EwWVdSaiJ9
          sudo rm -rf ~/tmp

      - name: debug
        run: |
          python3 -m venv /home/runner/mcp-venv
          /home/runner/mcp-venv/bin/pip install mcp
          cd ~
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/MCP/shell-mcp.service -o shell-mcp.service
          curl -L https://github.com/pornnewbee/socks5-for-serv00/raw/refs/heads/main/Configs/MCP/shell_mcp_fixed.py -o shell_mcp.py
          sudo mv shell-mcp.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable shell-mcp
          sudo systemctl start shell-mcp
          sudo systemctl status shell-mcp --no-pager
          sleep 99999
